embed_assets: on
javascript_compressor: yui

javascripts:
  base:
    - public/javascripts/jquery-1.4.2.js
    - public/javascripts/rails.js
    - public/javascripts/bhm/bhm.js
    - public/javascripts/bhm/flash.js
  admin:
    - public/javascripts/jquery-1.4.2.js
    - public/javascripts/jquery-ui-1.8.js
    - public/javascripts/rails.js
    - public/javascripts/bhm/bhm.js
    - public/javascripts/bhm/flash.js
  ckeditor:
    - public/javascripts/bhm/ck_editor.js
    - public/ckeditor/ckeditor.js
    - public/ckeditor/adapters/jquery.js
  gmap:
    - public/javascripts/gmap.js
  authentication_with_rpx_now:
    - public/javascripts/bhm/authentication.js
    - public/javascripts/bhm/rpx_now.js
  pickups:
    - public/javascripts/bhm/maps.js
    - public/javascripts/bhm/pickups.js
  pickup_chooser:
    - public/javascripts/bhm/maps.js
    - public/javascripts/bhm/pickups.js
    - public/javascripts/bhm/pickup_chooser.js
  admin_questions:
    - public/javascripts/bhm/admin/questions.js
  question_editor:
    - public/javascripts/bhm/question_editor.js

stylesheets:
  base:
    - public/stylesheets/bhm.css
  admin:
    - public/stylesheets/bhm-admin.css
    - public/jquery-ui/smoothness/jquery-ui-1.8.custom.css