javascript_compressor: yui
javascripts:
  base:
    - public/javascripts/vendor/jquery-1.4.2.js
    - public/javascripts/vendor/jquery.placeholder.js
    - public/javascripts/vendor/rails.js
    - public/javascripts/vendor/css_browser_selector.js
    - public/javascripts/vendor/facybox.js
    - public/javascripts/vendor/shuriken/**/*.js
    - public/javascripts/vendor/youthtree/**/*.js
    - public/javascripts/bhm/bhm.js
    - public/javascripts/bhm/flash.js
    - public/javascripts/bhm/debug.js
    - public/javascripts/vendor/jquery.tipsy.js
  clustered_map:
    - public/javascripts/vendor/markerclusterer.js
  admin:
    - public/javascripts/vendor/jquery-1.4.2.js
    - public/javascripts/vendor/jquery.placeholder.js
    - public/javascripts/vendor/jquery-ui-1.8.js
    - public/javascripts/vendor/rails.js
    - public/javascripts/vendor/facybox.js
    - public/javascripts/vendor/shuriken/**/*.js
    - public/javascripts/bhm/bhm.js
    - public/javascripts/bhm/flash.js
  dashboard:
    - public/javascripts/vendor/highcharts.js
    - public/javascripts/bhm/admin/charts.js
    - public/javascripts/bhm/admin/analytics.js
    - public/javascripts/bhm/admin/dashboard_stats.js
  ckeditor:
    - public/javascripts/bhm/ck_editor.js
    - public/ckeditor/ckeditor.js
    - public/ckeditor/adapters/jquery.js
  gmap:
    - public/javascripts/vendor/bhm-google-maps/*.js
  authentication_with_rpx_now:
    - public/javascripts/bhm/authentication.js
    - public/javascripts/bhm/rpx_now.js
  pickups:
    - public/javascripts/bhm/maps.js
    - public/javascripts/bhm/pickups.js
  pickup_chooser:
    - public/javascripts/bhm/maps.js
    - public/javascripts/bhm/pickups.js
    - public/javascripts/bhm/pickup_chooser.js
  admin_questions:
    - public/javascripts/bhm/admin/questions.js
  question_editor:
    - public/javascripts/bhm/admin/question_editor.js
  pickup_editor:
    - public/javascripts/bhm/admin/pickup_editor.js
  dynamic_template_editor:
    - public/javascripts/bhm/admin/dynamic_template_editor.js
  ie6:
    - public/javascripts/vendor/DD_belatedPNG_0.0.8a.js
    - public/javascripts/bhm/ie6.js
  postcode_mapper:
    - public/javascripts/vendor/markerclusterer.js
    - public/javascripts/bhm/maps.js
    - public/javascripts/bhm/admin/postcode_mapper.js
  share_this:
    - public/javascripts/bhm/share_this.js
  mission_dashboard:
    - public/javascripts/vendor/markerclusterer.js
    - public/javascripts/bhm/admin/mission_dashboard.js
  email_editor:
    - public/javascripts/bhm/admin/email_editor.js
stylesheets:
  base:
    - public/stylesheets/bhm.css
  admin:
    - public/stylesheets/bhm-admin.css
    - public/jquery-ui/smoothness/jquery-ui-1.8.custom.css
