development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bighelpmob_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test: &TEST
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bighelpmob_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bighelpmob_production
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock

cucumber:
  <<: *TEST