development:
  adapter: postgresql
  encoding: utf8
  database: bighelpmob_development
  user: bighelpmob
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: bighelpmob_test
  user: bighelpmob
  password:

staging:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: bighelpmob_staging
  user: bighelpmob
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: bighelpmob_production
  user: bighelpmob
  password:

cucumber:
  <<: *TEST
