#!/usr/bin/env ruby

ENV['RAILS_ENV'] ||= 'development'
require File.expand_path('../../config/environment',  __FILE__)

require 'daemon_spawn'

class ResqueWorkerDaemon < DaemonSpawn::Base

  def start(args)
    redirect_log!
    ActiveRecord::Base.establish_connection if defined?(ActiveRecord::Base)
    @worker = Resque::Worker.new('*') # Specify which queues this worker will process
    puts "Starting up resque worker: #{@worker.to_s}"
    @worker.verbose = 1 # Logging - can also set vverbose for 'very verbose'
    @worker.work
  end

  def stop
    @worker.try(:shutdown)
  end

  def redirect_log!
    config                    = Rails.application.config
    logger                    = ActiveSupport::BufferedLogger.new(STDOUT)
    logger.level              = ActiveSupport::BufferedLogger.const_get(config.log_level.to_s.upcase)
    logger.auto_flushing      = true
    Rails.logger              = logger
    ActiveRecord::Base.logger = logger
  end

end


logs = Rails.root.join("log", "resque_workers.#{Rails.env}.log").to_s
pids = Rails.root.join('tmp', 'pids', "resque_workers.#{Rails.env}.pid").to_s

ResqueWorkerDaemon.spawn!({
  :processes   => 1,
  :log_file    => logs,
  :pid_file    => pids,
  :sync_log    => true,
  :working_dir => Rails.root,
  :singleton   => true
})